### ISSUE TITLE
Have an option to disable realtime

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/JavaScriptSDK#10]
You can disable realtime when you init your CloudApp. 

`CB.CloudApp.init('https://api.cloudboost.io', 'Your AppID', 'YourAppKey',{disableRealtime : true});`

**Comment by gabrielAnglada** [comment]
Hi Nawaz, after updating and changing the init sigunature, after a login, the server returns this error

Your CloudApp is disconnected. Please use CB.CloudApp.connect() and try again.`

Do I need to make any change in the login flow?

**Comment by nawazdhandala** [comment]
What is your init signature?

**Comment by gabrielAnglada** [comment]
CB.CloudApp.init('https://api.cloudboost.io', 'Your AppID', 'YourAppKey',{disableRealtime : true}); as you commented before

**Comment by nawazdhandala** [comment]
Let me check this up real quick.

**Comment by gabrielAnglada** [comment]
If I do {disableRealtime : false} all is working fine (except the annoying message "WebSocket connection to 'wss://api.cloudboost.io/socket.io/?EIO=3&transport=websocket&sid=KxEWVZsvYtX8IcOXAAHs' failed: Connection closed before receiving a handshake response")

Thanks!

**Comment by nawazdhandala** [comment]
Thanks for letting me know. I'm on it.

**Comment by gabrielAnglada** [comment]
Hi Nawaz! Have you got any news about this?

Thanks!

**Comment by nawazdhandala** [comment]
One of our engineers is looking into this. I'll keep you posted. Please expect 2 day turn around.

**Comment by gabrielAnglada** [comment]
Any news about this?

Thanks!

**Comment by nawazdhandala** [comment]
Yep. We're working on this now however this seems to be working on our end without any problems.

**Comment by nawazdhandala** [comment]
Fixed. Can you please recheck.

**Comment by gabrielAnglada** [comment]
Nothing has changed in version 1.1.218.

If disableRealtime == true I cannot login and message `Your CloudApp is disconnected. Please use CB.CloudApp.connect() and try again.` is displayed in console

If disableRealtime == false, the annoying error message is displayed in console.

**Comment by nawazdhandala** [comment]
This works on our end. Can you please send me the line where you init the app.

**Comment by gabrielAnglada** [comment]
CB.CloudApp.init('https://api.cloudboost.io', 'AppId', 'ClientKey', {disableRealtime : true});

Thanks!

**Comment by nawazdhandala** [comment]
Creating a sample app and checking it out. CI tests pass though. :)

**Comment by nawazdhandala** [comment]
Found the bug. Fixing it.

**Comment by nawazdhandala** [comment]
Fixed. Can you please check. Thank you so much for your patience.

**Comment by gabrielAnglada** [comment]
It works!
