### ISSUE TITLE
Public read and write access to user data

### ISSUE THREAD

**Issue by blacksector** [CloudBoost/JavaScriptSDK#11]
Ok so after taking a look at the CloudBoost.io website and creating a test app I noticed that the app when creating a user it actually sets the ACL for public read AND write access. Now wouldn't that been an issue if anyone with the app key could simply change the password? How could one overcome that? 

For password resets a server can always be used to set the data manually... ? Or would that not work...?

Is it safe to have the data open to public reading and writing access?

**Comment by nawazdhandala** [comment]
You can use ACL's and User Sessions to only allow specific user to have access to their data. 
Check : https://tutorials.cloudboost.io/en/datastorage/files

OR, You can create your server and use our NodeJS library. In this case CloudBoost will not act as a backend but it'll act like a database instead.
