### ISSUE TITLE
query.paginate() API. 

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/JavaScriptSDK#12]
When paginating, it is interesting that server return more info about the total num items or the number of pages based on limit parameter.

Now, find method is returning directly an array of results. Maybe is interesting to modify it like this:

`
response: {
   totalResults: integer,
   data: array of results
}
//or
response: {
   pages: integer,
   currentPage: integer,
   data: array of results
}
`

Thanks!

**Comment by nawazdhandala** [comment]
Hmm.... You can do the query.count() to get totalResults. Do you think you still need this API?

**Comment by gabrielAnglada** [comment]
I would prefer to do only one query. It,s a minor issue, but when paginating, this is the expected result. If I use 2 queries (one for find and another for count) I need to nest them and the response time is slower.

Thanks!

**Comment by nawazdhandala** [comment]
Yes. I think for this, We need to create the new paginate API. If we change the API of find then this will break all the current apps that is built on top of that API. 

So, I think we should work on something like this :

query.paginate(pageNo, totalItemsInPage, callback);

What do you think?

**Comment by nawazdhandala** [comment]
I'll also keep this issue on low priority. Expected turn around for this should be in around a month. :)

**Comment by gabrielAnglada** [comment]
The idea is to continue using skip and limit query params. Then, instead of creating a new method, i would modify find by adding a second optional parameters called options. One of this options could be responseFormat with values "list" or "paginated_list". By default, value for this option property should be "list" and results are returned in the same way than now. If "paginated_list" is set,mthe results are returned in the format I proposed in the message above.

What do you think!

**Comment by nawazdhandala** [comment]
I honestly think that'll make the API a little too complicated. Can query.paginate() work?

**Comment by gabrielAnglada** [comment]
Sure! but I think it is no needed to add pageNo & totalItemsInPage arguments. Only with callback and setting before limit and skip would be enough.

**Comment by nawazdhandala** [comment]
Awesome! I'll keep those params optional. If limit and skip are set then it would take that. :)

**Comment by nawazdhandala** [comment]
Expect this to be turned around in couple of days. :)

**Comment by nawazdhandala** [comment]
This is done. :)

**Comment by gabrielAnglada** [comment]
Hi Nawaz!

While paginate() API first page need to be > 0, find() API first page could be 0. 

I think you must do the same in both case, I mean, make that first page in paginate() API can be 0.

What do you think?

**Comment by nawazdhandala** [comment]
Sorry for the late reply. I think paginate takes in the pageNo as params and find takes in items to be skipped and retrieved in params. So, the current version is fine in my view. What do you think?

**Comment by gabrielAnglada** [comment]
Do you remember that we talked about mantain current limit and skip properties in CloudQuery? If I set these values before call paginate(), I don't need to pass pageNo & totalItemsInPage. Then, these two params must be optional and then the paginate signature should be paginate(callback, pageNo, totalItemsInPage) with the last two arguments optional.

In fact, I suggest not to include this two arguments in method and use always limit and skip properties. You can throw an exception in paginate() API if this two properties are not set.

If you do this, you can use skip with value 0 (then you need to change the paginate method implementation) and you can be more consistent between methods.

What do you think?

**Comment by nawazdhandala** [comment]
I think the two params are optional, and you can directly pass in the callback and get the results. Let me know what you think? :)

**Comment by gabrielAnglada** [comment]
Personally, I prefer the method like this paginate(callback) and set limit and skip previous to call method. paginate() shoud throw an exception if limit and skip are not set. The decision is yours.

**Comment by nawazdhandala** [comment]
You can use it that way too. :)

**Comment by gabrielAnglada** [comment]
Ye, but this params must go after callback param in paginate function.
