### ISSUE TITLE
Make CloudUser session cooki expires after 1 year or configurable

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/JavaScriptSDK#13]
I think now the expiring time is set to 1 month, isn't it?

**Comment by nawazdhandala** [comment]
Yes, Its one month.

**Comment by nawazdhandala** [comment]
But this is a great feature, We're sure to add this. :)

**Comment by gabrielAnglada** [comment]
Any time prevision?

Thanks!

**Comment by nawazdhandala** [comment]
About 20 days.

**Comment by gabrielAnglada** [comment]
Hi Nawaz, what about this?

**Comment by nawazdhandala** [comment]
This is done. Check authentication section in app settings.
