### ISSUE TITLE
websocket problem

### ISSUE THREAD

**Issue by csotomon** [CloudBoost/JavaScriptSDK#15]
Hi, when I use the library in a ionic application, and I test it with chrome with the ionic serve command.

The library is giving me this error:

wss://api.cloudboost.io/socket.io/?EIO=3&transport=websocket&sid=LxEWXZsvYtX8IcOCAAHs' failed: Connection closed before receiving a handshake response.

**Comment by nawazdhandala** [comment]
Checking this out. Will keep you posted.
