### ISSUE TITLE
loginwithprovider problem

### ISSUE THREAD

**Issue by jantsch** [CloudBoost/JavaScriptSDK#16]
Hi, I am developing a sign in page using ngcordova. I get the access_token of all of the providers that I want, however when I try to authenticate with CloudBoost , it returns this error "Failed to load resource: the server responded with a status of 400". Is there any error in the function loginwithprovider? (or am I just doing something wrong?) Thanks!

**Comment by nawazdhandala** [comment]
Can we have your code please? Are you saving Social Authentication Settings in the dashboard?

**Comment by jantsch** [comment]
Yes.  I am initializing the cloudboost SDk inside my ".run" function of Angular.  
        var appId = "XX"; //My app ID is here
        var appKey = "YY"; // My Client ID is here
        CB.CloudApp.init(appId, appKey);
Then inside my controller of the signin, I have this.

 $scope.login_facebook = function ()
    {
        // Where KK is my facebook APP ID. 
        $cordovaOauth.facebook("KK", ["email", "public_profile"]).then(function (result) {
            console.log(JSON.stringify(result));
            CB.CloudUser.authenticateWithProvider({
                provider: "facebook",
                accessToken: result.access_token
            }, {
                success: function (user) {
                    console.log(user);
                },
                error: function (error) {
                    console.log(error);
                }
            });
            });
    }

The same facebook APP ID is configured on dashboard and the APP secret is given by facebook portal.  With your authentication page,all works fine(if I change the callback URL). I am having the same error with all my providers. ( Facebook, Twitter and Google).  I don't know if i should send everything. Thanks for the support!

**Comment by RTBathula** [comment]
Check Below points
==================
1. Go to your App Settings in https://dashboard.cloudboost.io, 
Under Auth Settings section, Add a)Your App callback URL,b) Enable Facebook Auth, add Facebook App Id, App Secret and then save.

2. In CB.Init() of your app, pass your CloudBoost AppId and ClientId

3. Either use CloudBoost Auth login page or make your own and get Facebbok "accessToken".

4. Now use CB.CloudUser.authenticateWithProvider({provider:"facebook", accessToken:"your facebook accessToken"});

**Comment by jantsch** [comment]
Hey, Thanks for the attention. I am doing EXACTLY the same as you described.  I am suspecting that the "cordovaOauth" is not returning it correctly. All the other requests that i do are ok. The only problem is to create the user using a social provider.

**Comment by jantsch** [comment]
It is returing correctly since I can get values of my account from facebook.
