### ISSUE TITLE
Bug with url variable in some api methods

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/JavaScriptSDK#18]
The next api methods must change:

`
url = CB.apiUrl + "/data/" + CB.appId + "/" + thisObj.tableName + '/<method>';
`

by

`
var url = CB.apiUrl + "/data/" + CB.appId + "/" + thisObj.tableName + '/<method>';
`

- CB.CloudQuery.prototype.distinct()
- CB.CloudQuery.prototype.find()
- CB.CloudQuery.prototype.findOne()

Also look at:

- CB.CloudFile.prototype.save()
- CB.CloudUser.getCurrentUser()
- CB.CloudUser.resetPassword()
- CB.CloudUser.prototype.signUp()
- CB.CloudUser.prototype.changePassword()
- CB.CloudUser.prototype.logIn()
- CB.CloudUser.authenticateWithProvider()
- CB.CloudUser.prototype.logOut()
- CB.CloudUser.prototype.addToRole()
- CB.CloudUser.prototype.removeFromRole()

If not, you are overriding the window.url function

**Comment by gabrielAnglada** [comment]
Please, fix this as soon as possible because it is causing some critical errors when integrating with other libraries

**Comment by nawazdhandala** [comment]
What the problem here? I'm not sure if I get this right. Can you please explain me a little more?

**Comment by gabrielAnglada** [comment]
The problem is that in functions that i have mentioned, url variable is not defined locall.

**Comment by nawazdhandala** [comment]
I'll get this done right away.
