### ISSUE TITLE
Warning when using cloudboost installed by npm. (Critical dependencies)

### ISSUE THREAD

**Issue by matiit** [CloudBoost/JavaScriptSDK#3]
When trying to build my project which uses (trying to use actually) your sdk I got this:

![image](https://cloud.githubusercontent.com/assets/138194/12006243/605ac3aa-abc6-11e5-9383-23a01a88ecf8.png)

In package.json I got following line:

```"cloudboost": "^1.1.137",```

NPM version is ```2.14.12```
Nodejs version is ```v4.2.4```

Host OS is Ubuntu 15.10

**Comment by matiit** [comment]
I might have ruhed a little bit with that issue.

The error part wasn't problem with CloudBoost SDK. 
I fixed that by adding following snippet to my webpack config:

```
  node: {
    fs: "empty"
  },
```

So, there only is the problem with warnging, which makes this issue far less priority.

**Comment by buhiirekeneth** [comment]
Hey,

Its good to know that you have solved the problem.

Incase of any question you can always reach out.

Happy new year.

Cheers

Sent from my Windows Phone
________________________________

**Comment by nawazdhandala** [comment]
Will fix the warning up right away Matiit. Thank you for letting me know. :)
