### ISSUE TITLE
SAMEORIGIN issue

### ISSUE THREAD

**Issue by telvin** [CloudBoost/JavaScriptSDK#30]
This issue happens randomly. I have made a simple query and this sometimes was just hang and then returned the 524 error. 

I noticed it just often happens on my remote server, my local machine does not experience this issue.

Below is my query
```
var query = new CB.CloudQuery("apps");
        query.equalTo("app_key", data.app_key);
        query.findOne({
            success: function (obj){},
            error: function (err){
                console.log(err.message);
}
});
```

Here is the error log
 

> { Error: Request failed with status code 524
>     at createError (/server/node_cb/node_modules/axios/lib/core/createError.js:15:15)
>     at settle (/server/node_cb/node_modules/axios/lib/core/settle.js:18:12)
>     at IncomingMessage.handleStreamEnd (/server/node_cb/node_modules/axios/lib/adapters/http.js:168:11)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> From previous event:
>     at new Promise (/server/node_cb/node_modules/cloudboost/dist/cloudboost.js:196:28)
>     at CloudBoost._CB2.default._request (/server/node_cb/node_modules/cloudboost/dist/cloudboost.js:6379:16)
>     at CloudQuery.findOne (/server/node_cb/node_modules/cloudboost/dist/cloudboost.js:20654:27)
>     at App.createApp (/server/node_cb/build/es5/app/main/entity-bases/app/App.js:30:15)
>     at AppController.createApp (/server/node_cb/build/es5/app/main/modules/authentication/AppController.js:72:13)
>     at ActionMetadata.executeAction (/server/node_cb/build/es5/src/metadata/ActionMetadata.js:258:62)
>     at /server/node_cb/build/es5/src/RoutingControllerExecutor.js:74:33
>     at process._tickCallback (internal/process/next_tick.js:103:7)
>   config:
>    { transformRequest: { '0': [Function: transformRequest] },
>      transformResponse: { '0': [Function: transformResponse] },
>      headers:
>       { Accept: 'application/json, text/plain, */*',
>         sessionID: '0c8f92b0-d612-11e6-9f72-05df06c86062',
>         'Content-Type': 'application/json;charset=utf-8',
>         'User-Agent': 'axios/0.14.0',
>         'Content-Length': 136 },
>      timeout: 0,
>      xsrfCookieName: 'XSRF-TOKEN',
>      xsrfHeaderName: 'X-XSRF-TOKEN',
>      maxContentLength: -1,
>      validateStatus: [Function: validateStatus],
>      method: 'POST',
>      url: 'https://api.cloudboost.io/data/igvlwbwaypaq/apps/findOne',
>      data: '{"query":{"$include":[],"$includeList":[],"app_key":"cine"},"select":{},"sort":{},"skip":0,"key":"81a49b6b-394f-41c8-aaf4-b37be2cead0e"}',
>      onUploadProgress: [Function: onUploadProgress] },
>   response:
>    { status: 524,
>      statusText: 'Origin Time-out',
>      headers:
>       { date: 'Mon, 09 Jan 2017 02:47:12 GMT',
>         'content-type': 'text/html; charset=UTF-8',
>         'transfer-encoding': 'chunked',
>         connection: 'close',
>         'set-cookie': [Object],
>         expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
>         'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
>         pragma: 'no-cache',
>         'x-frame-options': 'SAMEORIGIN',
>         server: 'cloudflare-nginx',
>         'cf-ray': '31e48dbfdf132a4f-SEA' },
> 

There are two requests were sent, one is using POST and one is using OPTIONS method

```
Request URL:https://api.cloudboost.io/data/igvlwbwaypaq/app_types/find
Request Method:OPTIONS
Status Code:204 
Remote Address:104.28.25.36:443
Response Headers
access-control-allow-headers:content-type, sessionid
access-control-allow-methods:GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin:*
```

and the second one will hang and return 504 error

```
Request URL:https://api.cloudboost.io/data/igvlwbwaypaq/app_types/find
Request Method:POST
Status Code:524 
Remote Address:104.28.25.36:443
Response Headers
cache-control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-ray:31e5589f2dc632ef-HKG
content-type:text/html; charset=UTF-8
date:Mon, 09 Jan 2017 05:05:42 GMT
expires:Thu, 01 Jan 1970 00:00:01 GMT
pragma:no-cache
server:cloudflare-nginx
set-cookie:__cfduid=d35719d5eea61e75dd7aae53c60e222191483938242; expires=Tue, 09-Jan-18 05:04:02 GMT; path=/; domain=.cloudboost.io; HttpOnly
status:524
x-frame-options:SAMEORIGIN
```

My server is  Ubuntu 16.04.1 LTS and Node v6.9.1. This issue is pretty annoying since it makes the app looks very unstable to use.

**Comment by nawazdhandala** [comment]
This is a known issue. We're investigating. :)

**Comment by nawazdhandala** [comment]
Should be fixed now. :)
