### ISSUE TITLE
CB.CloudApp is undefined.

### ISSUE THREAD

**Issue by matiit** [CloudBoost/JavaScriptSDK#4]
I installed library by ```npm install cloudboost```

Using this as following:

```
var CB = require('cloudboost');

console.log(CB.CloudApp);
```

The result is unfortunately undefined.

I double checked whether I am not missing anything, but I think I am doing it right.. no success though.

So, either docs aren't correct or something in library is broken. 

I will try to read the source code to seek the problem, but maybe I am not the only one who is stuck at the very beginning when trying to use this sdk?

**Comment by nawazdhandala** [comment]
Hi Matiit, 

All of our Nodejs tests pass though. Let me create a sample project and try again. Please give me an hour or so and I'll get back. 

Thanks

**Comment by matiit** [comment]
Ok, thanks for quick response.

**Comment by nawazdhandala** [comment]
@matiit  I dont think require("cloudboost") returns undefined. We have tested this on : https://tonicdev.com/npm/cloudboost 

![image](https://cloud.githubusercontent.com/assets/2697338/12006839/6c520d8a-abc6-11e5-9942-77b03cd7872b.png)

I'm now testing this by creating a sample project.

**Comment by nawazdhandala** [comment]
@matiit  Tested this on my machine. Works perfectly fine. :)

**Comment by matiit** [comment]
Thanks for such a quick reaction.

So it has to be a problem with my specific npm/nodejs versions.

I'll figure it out by myself.

**Comment by nawazdhandala** [comment]
You're welcome, Let me know if you need any more help. Happy holidays and a happy new year!
