### ISSUE TITLE
CloudSearch not working

### ISSUE THREAD

**Issue by ederribeiro** [CloudBoost/JavaScriptSDK#5]
Hi, i'm trying use this code: 
`var cs = new CB.CloudSearch('Collection');
cs.searchQuery = new CB.SearchQuery();
cs.searchQuery.searchOn(['title', 'description'], query);
cs.search({
success: function(list) { },
error: function(error) {}
});`

But, this return an empty array, always...

**Comment by nawazdhandala** [comment]
Whats your query?

**Comment by ederribeiro** [comment]
Any letter, any word, even researching the existing title at table nothing is returned.

**Comment by nawazdhandala** [comment]
Try with cs.searchQuery.searchOn(['title', 'description'], query, 2, null, "50%" );

which sets fuzziness to 2 and sets match percent to 50% or less. :)

https://docs.cloudboost.io/#sq-searchOn

Let me know if this works. :)

**Comment by ederribeiro** [comment]
not yet, nothing is returned... :(

**Comment by nawazdhandala** [comment]
Can you try saving new data and see if that works. I will try creating a sample app from my end and will  send you the repo.

**Comment by nawazdhandala** [comment]
@ranjeet692 is working on a sample project now. :)

**Comment by ederribeiro** [comment]
Well, i save new data to table and search works with restriction.
Example: Title is "Apple", only works if i search the terms (app, ple, ppl).

And my old data still are not appearing.

@nawazdhandala thanks a lot!

I really appreciate cloudboost.io.

**Comment by nawazdhandala** [comment]
You're most welcome. Search is still in its infancy right now and we're working on a new indexing engine to make it more relevant.

**Comment by nawazdhandala** [comment]
Do you still need a sample app from @ranjeet692 ?

**Comment by ederribeiro** [comment]
I think that is good for community, too. ;)

**Comment by nawazdhandala** [comment]
Here is the sample app from @ranjeet692  https://github.com/CloudBoost/SampleSearchApp. I am closing this issue now and have created the new issue #6 which will help us improve the relevancy of the search results.
