### ISSUE TITLE
React-native problem

### ISSUE THREAD

**Issue by aminesig** [CloudBoost/JavaScriptSDK#53]
Hello,
I have started playing with the Cloudboost js sdk with react native but RN chrome debugger console shows that the js runtime fails with " a document is not defined" exception on the CB init, Ofcourse this is possible given that RN doesn't handle 'document.createElement' which was thrown at the line 9505-from the cloudboost.js file, is there any solution for this problem ?
![issue](https://cloud.githubusercontent.com/assets/2048486/23681239/8cd24676-038e-11e7-9341-b96ebd152b52.png)

**Comment by nawazdhandala** [comment]
Thank you for letting us know. We're working on it. :)

**Comment by shubhamqweasd** [comment]
Please update the cloudboost sdk and try again.

**Comment by aminesig** [comment]
Still having the same problem :(

**Comment by shubhamqweasd** [comment]
there was some error while deploying, please check v1.3.9

**Comment by aminesig** [comment]
Perfect ! working now, thank you very much 👍
