### ISSUE TITLE
Improve Search Results. 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/JavaScriptSDK#6]
Have 1 fuzziness by default and 75% match percent.

**Comment by ederribeiro** [comment]
do you have a prediction on this?
it really is preventing me to continue and I will have to switch service because of it.

**Comment by nawazdhandala** [comment]
Sure, We're already working on it. Should be done in 2 weeks from now.

**Comment by ederribeiro** [comment]
Hi,
Do you have something new about this issue?

**Comment by nawazdhandala** [comment]
Hi @ederribeiro This issue is expected to resolve by Feb 29th of this month. :) We got to upgrade to new ElasticSearch cluster which has new API's, but please be sure that CloudBoost API's will not change.

**Comment by ederribeiro** [comment]
Hi @nawazdhandala this issue has been fixed?

**Comment by nawazdhandala** [comment]
Not yet @ederribeiro. We're working hard on this. This should be fixed very soon.

**Comment by nawazdhandala** [comment]
Integrating search into MongoDB,
