### ISSUE TITLE
How to save by column id

### ISSUE THREAD

**Issue by hanagejet** [CloudBoost/JavaScriptSDK#61]
I wanna save by column id.

Have like a table.

```js
{
  "id": 123456, // column id
  "items": [{
    "id": 1,
    "string": "foo",
  }]
}
```

Like this code.
```js
var obj = new CB.CloudObject('TableName');
obj.set("items", update_array);
obj.save('123456', { // column id
success: function(obj) {
},
error: function(err) {
}
});
```

Can I resolve??

**Comment by nawazdhandala** [comment]
I'm sorry, this code is incorrect. Please read https://tutorials.cloudboost.io/en/datastorage/objects for correct usage of the SDK. :)

**Comment by hanagejet** [comment]
@nawazdhandala
> this code is incorrect.

I know...

I already read: https://tutorials.cloudboost.io/en/datastorage/objects#UpdatingObjects
But can not save **by object id**.

**Comment by hanagejet** [comment]
So this is problem.

https://tutorials.cloudboost.io/en/datastorage/objects#SavingObjects
```js
obj.set('ColumnName', newData);
obj.save({
    success : function(obj){
        console.log(obj.id); //id is the same.  **👈 is not the same.**
    },error : function(error){
        //object failed to save. 
    }
});
```

**Comment by shubhamqweasd** [comment]
@hanagejet , you don't need id for updating/saving an Object , just modify any object data and call obj.save() ..
If you want to have a separate ID field on an Object other than what we already have , then you can set that explicitly by obj.set("ID_FILED", value) , and then save that object.

**Comment by hanagejet** [comment]
@shubhamqweasd Thanks reply :)
I try your code.

```js
obj.set('id_filed', '123456')
obj.set('items', {id: 1, foo: 'new bar'})
```

But is not the same column. So new column is created. Can I update column??

**Comment by hanagejet** [comment]
Ah, I missunderstand.

I success this.
```
query.findById(`${cloudBoostId}`, {
  success: (obj) => {
    console.log(obj);
    obj.set('items', items);
    obj.save({
      success: (list) => {
        console.log(list);
      },
      error: (error) => {
        console.log(error);
      },
    });
  },
  error: (obj) => {
    console.log(obj);
  },
});
```

Thanks cool members!!

**Comment by nawazdhandala** [comment]
You're welcome.
