### ISSUE TITLE
You cannot login the user on the server.

### ISSUE THREAD

**Issue by akacode** [CloudBoost/JavaScriptSDK#64]
Hi!

I'm testing CloudBoost (dockerized) with a React native app, all is going good until then, when I try make login following the documentation I got this error: You cannot login the user on the server.

The user signup is ok, I can see it on user lists.

Seeing the source, in the line [266](https://github.com/CloudBoost/JavaScriptSDK/blob/master/src/CloudUser.js#L266) of CloudUser.js always throws this, the user credentials is ok.

![Error](https://image.ibb.co/b64GgQ/Captura_de_tela_de_2017_04_09_01_28_40.png)

Can you help me?

**Comment by nawazdhandala** [comment]
We've recognised this issue. I'll get it fixed first thing tomorrow morning and will let you know.

**Comment by akacode** [comment]
I'll wait for this fix and try again.
Thanks @nawazdhandala

**Comment by shubhamqweasd** [comment]
@akacode , this should be fixed , please update your sdk to the latest version i.e v2.0.251

**Comment by akacode** [comment]
Thanks @shubhamqweasd and @nawazdhandala
Now is working.
