### ISSUE TITLE
getting 400 error

### ISSUE THREAD

**Issue by sumanindusnet** [CloudBoost/JavaScriptSDK#66]
I am using cloudboost SDK to login but when the credentials are wrong instead of returning the error message in the error section of the callback function it it returning following I have attached in screenshot.

This is how I am calling the API and the response is in the attachment

var user = new CB.CloudUser();
user.set('username', 'my_username');
user.set('password', 'my_solid_password');
user.set('email', 'email@sample.com');
user.signUp({
success: function(user) {
//Registration successfull
},
error: function(err) {
//Error in user registration.
}
});

![untitled](https://cloud.githubusercontent.com/assets/13829449/25523221/7ab0ed54-2c23-11e7-8a0e-624ab5aceef4.png)

**Comment by nawazdhandala** [comment]
I think the response should be 401
If the request included authentication credentials, then the 401 response indicates that authorization has been refused for those credentials.
from https://httpstatuses.com/401

**Comment by sumanindusnet** [comment]
#65 
Yes, but instead of that getting 400 BAD REQUEST 
The server cannot or will not process the request due to something that is perceived to be a client error 
from https://httpstatuses.com/400 as a result the error section of the callback function is not returning the desire error object.

**Comment by nawazdhandala** [comment]
Will fix it.

**Comment by sumanindusnet** [comment]
Thanks, at the same time it would be great if I could have pass some additional params along with the username, password and email to validate a user on login, let say in my case I want to only some selected users to logged into the web panel but adding those fields in login api request does not work.

**Comment by nawazdhandala** [comment]
Unfortunately that's not in our feature backlog. What you can do is once the user is logged in, check those params on the client, if it does not match - you can log the user out immediately before redirecting him to the dashboard.
