### ISSUE TITLE
Session clear when the page is refreshed.

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/JavaScriptSDK#7]
http://stackoverflow.com/questions/35366925/mantain-session-user-in-cloudboost-using-javascript/35370979#35370979

**Comment by gabrielAnglada** [comment]
Thanks a lot for taking care of this!

**Comment by nawazdhandala** [comment]
You're welcome. :)

**Comment by blacksector** [comment]
https://github.com/CloudBoost/JavaScriptSDK/blob/master/src/CloudUser.js#L121

With that in mind, a possible solution is to maybe save it in local storage then retrieve it on page refresh?

**Comment by nawazdhandala** [comment]
Yes, We're building that in the SDK. It'll basically store it in local storage or a cookie. This should be fixed by Monday. Its an easy patch.

**Comment by nawazdhandala** [comment]
@gabrielAnglada @blacksector This is done! :) Please check and confirm,

**Comment by gabrielAnglada** [comment]
I have tested it in web browser and in cordova app on iPad and it works perfectly!

Thanks!

**Comment by nawazdhandala** [comment]
Thats good to know. You're welcome. I'm on resetPassword / changePassword API. That'll be out very soon. :)
