### ISSUE TITLE
Have API to resetPassword and changePassword in CloudUser

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/JavaScriptSDK#9]

**Comment by gabrielAnglada** [comment]
Be sure to add this two methods only for the current user and not for all CloudUser Objects. I don't want to change password of other people :P 

Thanks!

**Comment by nawazdhandala** [comment]
hahaha. Yes. Change Password will be for current user and reset password will be for all the users. You can't have a current user session if you're not able to log in (in the case of reset password).

**Comment by nawazdhandala** [comment]
This is done. Please check : https://tutorials.cloudboost.io/en/security/users

**Comment by gabrielAnglada** [comment]
Awesome! I will test it as soon as possible! I thinks there is something wrong with the documentation styling for this two new methods.

Thanks again!

**Comment by nawazdhandala** [comment]
We fixed the styling. Thank you! :)

**Comment by gabrielAnglada** [comment]
Your are fast! also remember to update this doc --> https://docs.cloudboost.io/#CloudUser

**Comment by gabrielAnglada** [comment]
Hi Nawaz! I have tested both methods and there is something wrong:

**changePassword**: It seems to work fine, the method goes to successCallback or errorCallback depending on the values submitted. But if I do a logout and a login, I cannot login with the new password but I can with the old one.

**resetPassword**: It seems to work fine, the method goes to successCallback or errorCallback depending on the values submitted. But I don't receive any email with the link to recover it (10 minutes since my last call to resetPssword)

Thanks!

**Comment by nawazdhandala** [comment]
Last time I checked, it was working. We even write tests for it. Let me check it again and get back to you. Can you post your sample code please.

**Comment by gabrielAnglada** [comment]
First I do:

`CB.CloudUser.current.changePassword(oldPassword, newPassword ,{
   success: function(user) {
      showAlert(''success message);
   },
   error: function(error) {
      showAlert(''error message);
   }
});`

After changing I do

`CB.CloudUser.current.logOut({
   success : function(user){
      window.location.href = '';
   }, error : function(error){
      showAlert(''error message);
   }
});`

And Finally I try to do login:

`var user = new CB.CloudUser();
user.set('username', username);
user.set('password', newPassword);
user.logIn({
   success: function(response) {
      //do something after login
   },error: function(error) {
      showAlert(''error message);
   }
});`

Then I cannot use the newPassword to login, I have to use the other one. 

But I have tested in other way and it doesn't work: After changing password (successCallback is achieve) I go inmediatelly to change password again and I the new password doesn't work, I have to write the old one.

**Comment by nawazdhandala** [comment]
Thanks! Chnage Password fixed. I'm now working on resetPassword.

**Comment by nawazdhandala** [comment]
Aparently production servers cannot communicate with mail servers. This works in development though. Investigating this issue. Should be fixed in about a day.

**Comment by nawazdhandala** [comment]
Fixed.

**Comment by gabrielAnglada** [comment]
Thanks Nawaz! I will test it as soon as I can. My mac is unavailable until tuesday :(

One more question: in documentation you talk about an emails section on app dashboard. Where is it? Is it available?

**Comment by nawazdhandala** [comment]
We're building the email dashboard on the portal, but you can still send emails. Email dashboard should be out by mid of next week.

**Comment by gabrielAnglada** [comment]
changePassword and rsetPassword work fine!

Thanks a lot!

I'll be waiting for email templating tool!

**Comment by gabrielAnglada** [comment]
Hi Nawaz, any news about email templatingnon dahsboard? Thanks!

**Comment by nawazdhandala** [comment]
Yes. A week from now that should be ready, :)

**Comment by gabrielAnglada** [comment]
Hi Nawaz, some feedback about reset password email templating.

1 - When I use *|NAME|* variable, nothing is displayed in the email

2 - It would be better that *|LINK|* variable was only the url, not all the button. I need to write the button label in spanish and I cannot do something like:

`<p><a href="*|LINK|*" target="_blank" style="background-color: rgb(255, 255, 255);">Cambiar contraseña</a></p>`

Thanks!

**Comment by nawazdhandala** [comment]
1 - I'll check it out. 

2 - Good idea. Working on it.

**Comment by nawazdhandala** [comment]
This is fixed. :)

**Comment by gabrielAnglada** [comment]
Hi Nawaz, I have edited the template in html mode (right button in the editor) and I added this markup to test how it is seen on an email:

`<p>*|LINK|*</p>

<p><a href="*|LINK|*">Cambiar contraseña</a></p>`

When the email is received this is what is displayed:

`*|LINK|*

Cambiar contraseña`

And this is the real markup generated:

`<p>*|LINK|*</p>
<p>Cambiar contraseña</p>`

Am I doing something wrong?

Other thing: NAME variable works fine :)

**Comment by nawazdhandala** [comment]
Looking into it today. :) I'll ping you back in few hours. :)

**Comment by gabrielAnglada** [comment]
Hi Nawaz, have you found any issues on this? Maybe you should reopen this issue until it is fixed.

Thanks!

**Comment by nawazdhandala** [comment]
I'm checking this out. I apologize for the late reply.

**Comment by gabrielAnglada** [comment]
Thanks! It works

**Comment by nawazdhandala** [comment]
You're welcome. Thank you for helping us make the service better every day.
